### ISSUE TITLE
[Suggestion] Increase size kill-streak counter

### ISSUE THREAD

**Issue by SheepishShepherd** [DarSitam/DarHud#18]
Would it be possible for you to make the kill-streak counter slightly bigger to support 3 digit numbers? It is unreasonable to get that high in casual, but in Man vs Machines its more than feasible. Some of the numbers are bigger and end up cutting off at the end of the number as shown here: 

![killstreak-counter](https://user-images.githubusercontent.com/36808587/214175765-4c53e4fd-af4c-4d31-aafd-929997fba3a8.png)

**Comment by DarSitam** [comment]
Can you check if the most recent update from the beta branch fix the issue ? I've increased the counter size

**Comment by SheepishShepherd** [comment]
I tested all the way up to 1000 with no issue; all the digits appear without trailing. The panel sometimes is a bit short but I wouldn't about it, since it'd probably would look weird having it too big for small numbers. I'm happy I at least can see what number it is. Thanks for doing this.
