### ISSUE TITLE
Killstreak element position overlaps with overheal cross

### ISSUE THREAD

**Issue by SheepishShepherd** [DarSitam/DarHud#22]
When overhealed, the white cross will overlap the killstreak counter as the image below shows. It originally was below the player portrait, so this issue has come about in the most recent version.
![image](https://user-images.githubusercontent.com/36808587/226062994-c3900d7a-956b-48ab-8786-76d86a9ff9bf.png)

**Comment by DarSitam** [comment]
Should be fixed now
