### ISSUE TITLE
[4:3 Specific] Killfeed Killstreak number overlaps with KS icon

### ISSUE THREAD

**Issue by TechnoSL** [DarSitam/darhud#25]
Resolution: 1280x960
i have no clue on how to make a good bug report
didn't test killstreaks above 2 digits, but it might also affect those

screenshot examples
![20230818192034_1](https://github.com/DarSitam/DarHud/assets/41777800/51881497-1de5-459b-9015-d19c7bbb7ebf)
![20230818192046_1](https://github.com/DarSitam/DarHud/assets/41777800/32c8923e-a332-4251-b334-cb61a142a305)

**Comment by DarSitam** [comment]
may i ask if you have downloaded the latest version of the hud ?

because with the latest commit, the killstreak value in the killfeed is clearer

![20230821212147_1](https://github.com/DarSitam/darhud/assets/106157297/1a43044e-95e1-44ad-a375-56fce4e84590)

**Comment by TechnoSL** [comment]
> may i ask if you have downloaded the latest version of the hud ?
> 
it was the latest version i had at the time, but it seems to be fixed now that i downloaded the latest version.
