### ISSUE TITLE
Transparent Viewmodels?

### ISSUE THREAD

**Issue by RalphORama** [DarSitam/darhud#28]
I really like this hud!

Is there a way to enable viewmodel transparency? I switched over from PeachHUD and my viewmodels are no longer transparent

I have this in `enable_transparency.cfg`:

```
mat_motion_blur_enabled 1
mat_motion_blur_strength 0
mat_disable_bloom 1
mat_hdr_level 0
mat_colcorrection_disableentities 1
mat_colorcorrection 0
```

Thanks!

**Comment by DarSitam** [comment]
doesnt this tutorial work with the hud ? https://www.youtube.com/watch?v=rsWPW817xWY

i never tested transparent viewmodels

**Comment by RalphORama** [comment]
> https://www.youtube.com/watch?v=rsWPW817xWY

this works! thank you for that. I tried a few other tutorials I found on YouTube but I think the custom materials were what was needed.
