### ISSUE TITLE
Impossible to select style

### ISSUE THREAD

**Issue by exzolink** [DarSitam/darhud#29]
Hello.
With hud installed is impossible to view style image and open selector.
https://imgur.com/u0sxL5m

UPD: Ok, now i can select styles, idk, maybe tf bug, but still can't see images

**Comment by exzolink** [comment]
And the rounded border look out of place, I think.
https://imgur.com/a/NqNyXzD

**Comment by DarSitam** [comment]
> And the rounded border look out of place, I think. https://imgur.com/a/NqNyXzD

i removed the corners in fb371c1cea8f6975daf0404b155f5fb807a815ca

**Comment by DarSitam** [comment]
> UPD: Ok, now i can select styles, idk, maybe tf bug, but still can't see images

fixed in 1d67f5cddd2b9994cd299597b50e60f667eba5a2
