### ISSUE TITLE
Wrong tooltip location

### ISSUE THREAD

**Issue by exzolink** [DarSitam/darhud#30]
https://imgur.com/CsQoccC

**Comment by exzolink** [comment]
> what happens when you click on it ? i don't have this button :/

Nothing, just music playing as if I clicked on the logo

**Comment by DarSitam** [comment]
@exzolink Can you confirm ?

**Comment by exzolink** [comment]
> @exzolink Can you confirm ?

Wait, why he has another interface?

**Comment by exzolink** [comment]
Ok, updated hud, tooltip still here
https://imgur.com/bF5KFXA

**Comment by DarSitam** [comment]
i managed to locate what it was exactly, it's fixed now 
1e01a75346ecdd342200f55b92a7435e704462fd

**Comment by exzolink** [comment]
Thank you
