### ISSUE TITLE
Supernova meter overlapping with timer

### ISSUE THREAD

**Issue by impale1** [DarSitam/darhud#32]
![ctf_hellfire0017](https://github.com/DarSitam/darhud/assets/117596825/971fa686-99f7-4c89-80e0-001202f3d94a)

Operating system: Windows 11 Enterprise 22H2
Resolution: 1920x1080

**Comment by DarSitam** [comment]
> `hudpowerupeffectmeter.res` -> `HudItemEffectMeter`
> 
> "xpos" "r220" "ypos" "r21"
> 
> ![ctf_hellfire0021](https://user-images.githubusercontent.com/117596825/266026009-73c455df-dcaf-45b3-80a9-ad570f30d5c2.png)

the problem with this solution is that the picked weapon box is also there
![20230907205602_1](https://github.com/DarSitam/darhud/assets/106157297/4ba16397-26ed-4981-9dfa-0e0de1cb8e7d)

but i think i'll move it elsewhere, the only problem is that i dont know where

**Comment by DarSitam** [comment]
done 801bf9f91612fe937d9092d930a646a06255ca16

![20230907212314_1](https://github.com/DarSitam/darhud/assets/106157297/c1834b79-c835-4eca-9ab3-581916ccc386)
