### ISSUE TITLE
long steam name overlaps stats on main menu

### ISSUE THREAD

**Issue by RalphORama** [DarSitam/darhud#36]
with the default install (commit d484d72), long steam names will overlap stats in the main menu

![image](https://github.com/DarSitam/darhud/assets/6566104/adb3e8eb-1ad0-4da5-9824-5f44c4c51c23)

**Comment by DarSitam** [comment]
sup ! should be fixed (finally)
![image](https://github.com/DarSitam/darhud/assets/106157297/b851e006-7925-47d6-9bca-496a4ebcd762)
aecd2476b3a055beaa4258806ca76e6d571b72c5
