### ISSUE TITLE
Medic patient HP is too small

### ISSUE THREAD

**Issue by Lightboom9** [DarSitam/darhud#38]
Title basically. As a medic it's pretty helpful to know how much health your patient has. It would be nice if you didn't have to squint to be able to tell.

**Comment by DarSitam** [comment]
something like this ?

![image](https://github.com/DarSitam/darhud/assets/106157297/54d18ae2-e2f2-46e5-bdd7-fa98c3175e59)

**Comment by Lightboom9** [comment]
Yeah this looks better. It's a little hard to tell from a cropped screenshot but bigger is better :D

**Comment by DarSitam** [comment]
https://github.com/DarSitam/darhud/commit/eb293785b041c7160f3dd97189dd695b380d9d8a
