### ISSUE TITLE
[Suggestion] Deafult-style mode selection

### ISSUE THREAD

**Issue by BlindSE** [DarSitam/darhud#40]
The current way of selecting a gamemode seems quite clunky due to taking up the entire screen, the side panel menu from the default game had its flaws but I grew very used to navigating it. Therefore I would like to see either a similar implementation or just an option to use the vanilla selection menu while retaining the rest of the stylized menu.

**Comment by SheepishShepherd** [comment]
- I too occasionally have issues with returning to a previous selection once ive navigated through the gamemode selections

**Comment by DarSitam** [comment]
will be done at one point

**Comment by DarSitam** [comment]
done 010fefc47a74613e661067514ff11c14b8909a1b
