### ISSUE TITLE
Party chat font is oversized and text on buttons is missaligned in the new ui beta

### ISSUE THREAD

**Issue by karmazogs** [DarSitam/darhud#46]
![Screenshot from 2024-08-21 11-51-54](https://github.com/user-attachments/assets/0a167421-554b-4a0e-8bb4-caf4390a499c)
![Screenshot from 2024-08-21 11-58-07](https://github.com/user-attachments/assets/28bfe432-a3a7-41e8-8ab6-98ad8c9075d8)

**Comment by DarSitam** [comment]
Now fixed c061f8c2e9052c5c530ccaaecf54a5bb3014e3f4
